### ISSUE TITLE
 Implement PayJoin  changes

### ISSUE THREAD

**Issue by openoms** [openoms/joininbox#15]
Currently there is an error accessing the auth_cookie on receiving a payjoin:

```
ERROR]  Setup failed: [Failure instance: Traceback: <class 'RuntimeError'>: Failed to connect to: <twisted.internet.endpoints.UNIXClientEndpoint object at 0xb4d4f5b0>: An error occurred while connecting: 13: Permission denied., <twisted.internet.endpoints.TCP4ClientEndpoint object at 0xb4d4f590>: Failed to read COOKIEFILE '/mnt/hdd/tor/sys/control_auth_cookie': [Errno 13] Permission denied: '/mnt/hdd/tor/sys/control_auth_cookie'
, <twisted.internet.endpoints.TCP4ClientEndpoint object at 0xb4d4f610>: Connection was refused by other side: 111: Connection refused.
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/txtorcon/controller.py:466:connect
]
Setup failed: [Failure instance: Traceback: <class 'RuntimeError'>: Failed to connect to: <twisted.internet.endpoints.UNIXClientEndpoint object at 0xb4d4f5b0>: An error occurred while connecting: 13: Permission denied., <twisted.internet.endpoints.TCP4ClientEndpoint object at 0xb4d4f590>: Failed to read COOKIEFILE '/mnt/hdd/tor/sys/control_auth_cookie': [Errno 13] Permission denied: '/mnt/hdd/tor/sys/control_auth_cookie'
, <twisted.internet.endpoints.TCP4ClientEndpoint object at 0xb4d4f610>: Connection was refused by other side: 111: Connection refused.
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/txtorcon/controller.py:466:connect
]
done
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
    status.deferred.errback()
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/payjoin.py", line 1114, in onion_listen
    return onion_ep.listen(self.site)
builtins.AttributeError: 'NoneType' object has no attribute 'listen'
```

**Comment by openoms** [comment]
Fixed in https://github.com/openoms/joininbox/commit/db595b0d06a111743bb4e8c68c19c6e412bee615
